//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace promotion_company.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Actions
    {
        public Actions()
        {
            this.Fines = new HashSet<Fines>();
            this.PromoterActions = new HashSet<PromoterActions>();
        }
    
        public int ActionId { get; set; }
        public string ActionName { get; set; }
        public Nullable<int> ActionTypeId { get; set; }
        public string Location { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> NeededPromoters { get; set; }
    
        public virtual ActionTypes ActionTypes { get; set; }
        public virtual ICollection<Fines> Fines { get; set; }
        public virtual ICollection<PromoterActions> PromoterActions { get; set; }
    }
}
