//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace promotion_company.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PromoterAgencySochnevEntities : DbContext
    {
        public PromoterAgencySochnevEntities()
            : base("name=PromoterAgencySochnevEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Actions> Actions { get; set; }
        public DbSet<ActionTypes> ActionTypes { get; set; }
        public DbSet<Fines> Fines { get; set; }
        public DbSet<PromoterActions> PromoterActions { get; set; }
        public DbSet<Roles> Roles { get; set; }
        public DbSet<Users> Users { get; set; }
    }
}
