//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace promotion_company.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PromoterActions
    {
        public int PromoterId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> ActionId { get; set; }
    
        public virtual Actions Actions { get; set; }
        public virtual Users Users { get; set; }
    }
}
