//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace promotion_company.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public Users()
        {
            this.Fines = new HashSet<Fines>();
            this.PromoterActions = new HashSet<PromoterActions>();
        }
    
        public int UserId { get; set; }
        public string FullName { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public int RoleId { get; set; }
    
        public virtual ICollection<Fines> Fines { get; set; }
        public virtual ICollection<PromoterActions> PromoterActions { get; set; }
        public virtual Roles Roles { get; set; }
    }
}
